### ISSUE TITLE
Recommend using coercible-utils instead

### ISSUE THREAD

**Issue by sjakobi** [sjakobi/newtype-generics#4]
Same thing, but fewer instances…

**Comment by treeowl** [comment]
`coercible-utils` gives lousy type inference, I believe. The passed `newtype` constructor links two of the type variables, but there will still be a pair of `Coercible` types that aren't connected. I think you should consider a separate module that *only* works with `Generic` instances.

**Comment by sjakobi** [comment]
I agree that the API that you propose in https://github.com/sjakobi/newtype-generics/pull/5 is superior.
